var sort_data = {
        "sort0":[
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"30"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"30"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"30"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"30"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"230"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"230"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"230"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"230"
            },
            {
                "title":"电脑系统重修",
                "pic":"img/10.png",
                "money":"230"
            }
            
        ],
    "sort1":[
        {	
        	"id"
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        }
        
    ],
    "sort2":[
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"3330"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"320"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        }
        
    ],
    "sort3":[
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        }
        
    ],
    "sort4":[
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        }
        
    ],
    "sort5":[
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        }
        
    ],
    "sort6":[
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        }
        
    ],
    "sort7":[
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"30"
        },
        {
            "title":"电脑系统重修",
            "pic":"img/10.png",
            "money":"230"
        }
        
    ]
}